version: "3.3"
services:
  postgres:
    container_name: postgres
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 2s
      retries: 10
      start_period: 5s

  db_updater:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: upd.Dockerfile
    depends_on:
      postgres:
        condition: service_healthy

  app:
    env_file:
      - .env
    build: 
      context: .
      dockerfile: app.Dockerfile
    restart: always
    depends_on:
      db_updater:
        condition: service_completed_successfully
